server:
  port: 9999
logging:
  level:
    com.music.demo: debug
spring:
  data:
    redis:
      host: 120.46.159.231
      username: default
      password: 2046
      database: 59
my:
  secretkey: sfne