
spring:
  application:
    name: search-service
logging:
  level:
    com.music.demo: debug
server:
  port: 30003
knife4j:
  enable: true
  setting:
    language: zh_cn
mypath: D:/data/test/
my:
  secretkey: sfne